# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        id: [0,1,2]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    - name: Test strategy
      run: |
        echo "Strategy ${{ matrix.id }}" >> output_${{ matrix.id }}.txt
    
    - name: Push Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ matrix.id }}
        path: output_${{ matrix.id }}.txt
        retention-days: 1
    
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact 0
        uses: actions/download-artifact@v4
        with:
          name: artifact-1
      
      - name: Download a single artifact 1
        uses: actions/download-artifact@v4
        with:
          name: artifact-1

      - name: Download a single artifact 2
        uses: actions/download-artifact@v4
        with:
          name: artifact-2
      
      - name: Result
        run: ls -la
